# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://bitpie.com
title: 测试而已
email: bithernet@gmail.com
author: getcai
description: > 学习gibhub,git
copyright: '&copy; 2016 bitpie.com.'
credits: 'bitpie Based on Bither Technology. <a href="http://bither.net">Bither</a>. <a href="http://chaincloud.com">ChainCloud</a>'
logo: img/logo.png
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email&test.com
    url: mailto:chainclouddotcom@gmail.com

 
